import { FullConfig } from '@playwright/test';
import axios from 'axios';
import fs from 'fs/promises';
import path from 'path';

async function globalTeardown(config: FullConfig) {
  console.log('🧹 Starting global teardown for Playwright tests...');
  
  try {
    // Clean up test database
    console.log('🗄️ Cleaning up test database...');
    await axios.post('http://localhost:3000/api/test/cleanup', {
      cleanupTestData: true
    });
    console.log('✅ Test database cleanup complete');
  } catch (error) {
    console.log('ℹ️ Test cleanup endpoint not available, skipping...');
  }
  
  // Generate test summary report
  console.log('📊 Generating test summary report...');
  await generateTestSummaryReport();
  
  // Organize test artifacts
  console.log('📁 Organizing test artifacts...');
  await organizeTestArtifacts();
  
  console.log('✅ Global teardown completed successfully!');
}

async function generateTestSummaryReport() {
  try {
    const resultsPath = path.join(process.cwd(), 'Tests', 'results');
    const reportPath = path.join(resultsPath, 'test-summary.md');
    
    // Read test results if available
    let testResults: any = null;
    try {
      const resultsFile = await fs.readFile(path.join(resultsPath, 'test-results.json'), 'utf-8');
      testResults = JSON.parse(resultsFile);
    } catch (error) {
      console.log('ℹ️ No test results file found');
    }
    
    const timestamp = new Date().toISOString();
    const summary = `
# Test Execution Summary

**Date:** ${timestamp}
**Environment:** Development
**Test Suite:** Tino 2 - Phase 10 End-to-End Testing

## Test Results Overview

${testResults ? `
- **Total Tests:** ${testResults.stats?.total || 'N/A'}
- **Passed:** ${testResults.stats?.passed || 'N/A'}
- **Failed:** ${testResults.stats?.failed || 'N/A'}
- **Skipped:** ${testResults.stats?.skipped || 'N/A'}
- **Duration:** ${testResults.stats?.duration ? Math.round(testResults.stats.duration / 1000) + 's' : 'N/A'}
` : `
- Test results will be populated after test execution
`}

## Test Artifacts

- **Screenshots:** Tests/results/screenshots/
- **Videos:** Tests/results/videos/
- **HTML Reports:** Tests/results/reports/
- **Performance Metrics:** Tests/results/metrics/

## Test Environment

- **Backend URL:** http://localhost:3000
- **Frontend URL:** http://localhost:3001
- **Test Data:** Automated seeding and cleanup
- **Browsers:** Chrome, Firefox, Safari, Mobile Chrome, Mobile Safari

## Next Steps

1. Review failed tests in HTML report
2. Analyze performance metrics
3. Address any issues found
4. Re-run affected test suites

---
Generated by Playwright Test Suite - Phase 10 Testing Framework
`;

    await fs.writeFile(reportPath, summary);
    console.log('✅ Test summary report generated');
    
  } catch (error) {
    console.log('⚠️ Failed to generate test summary report:', error);
  }
}

async function organizeTestArtifacts() {
  try {
    const resultsPath = path.join(process.cwd(), 'Tests', 'results');
    
    // Create timestamp-based directories for this test run
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const runDir = path.join(resultsPath, `run-${timestamp}`);
    
    await fs.mkdir(runDir, { recursive: true });
    
    // Move artifacts to organized structure
    const artifactDirs = ['screenshots', 'videos', 'reports', 'metrics'];
    
    for (const dir of artifactDirs) {
      const srcPath = path.join(resultsPath, dir);
      const destPath = path.join(runDir, dir);
      
      try {
        await fs.access(srcPath);
        await fs.rename(srcPath, destPath);
        console.log(`✅ Organized ${dir} artifacts`);
      } catch (error) {
        // Directory doesn't exist, skip
      }
    }
    
    // Recreate empty directories for next run
    for (const dir of artifactDirs) {
      await fs.mkdir(path.join(resultsPath, dir), { recursive: true });
    }
    
    console.log(`✅ Test artifacts organized in: ${runDir}`);
    
  } catch (error) {
    console.log('⚠️ Failed to organize test artifacts:', error);
  }
}

export default globalTeardown;