import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1777158117672 implements MigrationInterface {
    name = 'InitialSchema1777158117672'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bookingId" uuid NOT NULL, "customerId" uuid NOT NULL, "providerId" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "platformFee" numeric(10,2) NOT NULL DEFAULT '0', "processingFee" numeric(10,2) NOT NULL DEFAULT '0', "providerAmount" numeric(10,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'USD', "paymentMethod" character varying NOT NULL, "stripePaymentIntentId" character varying, "stripeChargeId" character varying, "paypalTransactionId" character varying, "stripeRefundId" character varying, "status" character varying NOT NULL DEFAULT 'pending', "metadata" jsonb, "paidAt" TIMESTAMP, "completedAt" TIMESTAMP, "failedAt" TIMESTAMP, "refundedAt" TIMESTAMP, "refundAmount" numeric(10,2) NOT NULL DEFAULT '0', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a25d33dbd8e95a1875d42ac40c" ON "payments" ("providerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_824be6feda5e655c49c4e0c534" ON "payments" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ead3dc5d71db0ea822706e389" ON "payments" ("bookingId") `);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" uuid NOT NULL, "providerId" uuid NOT NULL, "serviceType" character varying NOT NULL, "description" text NOT NULL, "location" jsonb NOT NULL, "scheduledDate" TIMESTAMP NOT NULL, "estimatedDuration" integer NOT NULL DEFAULT '60', "status" character varying NOT NULL DEFAULT 'pending', "totalAmount" numeric(10,2) NOT NULL, "paymentStatus" character varying NOT NULL DEFAULT 'pending', "specialInstructions" text, "additionalServices" jsonb, "timeline" jsonb, "confirmedAt" TIMESTAMP, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "stripePaymentIntentId" character varying, "holdPlacedAt" TIMESTAMP, "cancelledAt" TIMESTAMP, "cancellationReason" character varying, "isDisputed" boolean NOT NULL DEFAULT false, "disputeStatus" character varying, "disputeReason" character varying, "disputedAt" TIMESTAMP, "disputeResolution" character varying, "disputeResolvedAt" TIMESTAMP, "disputeResolvedBy" character varying, "adminNotes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_910f39bbc27a3fe62723500c01" ON "bookings" ("scheduledDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_48b267d894e32a25ebde4b207a" ON "bookings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f8605bc996f6c39ebd7dbead7" ON "bookings" ("providerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_67b9cd20f987fc6dc70f7cd283" ON "bookings" ("customerId") `);
        await queryRunner.query(`CREATE TABLE "quote_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" uuid NOT NULL, "serviceType" character varying NOT NULL, "description" text NOT NULL, "location" jsonb NOT NULL, "preferredDate" TIMESTAMP, "budget" jsonb, "images" jsonb, "urgency" character varying NOT NULL DEFAULT 'medium', "status" character varying NOT NULL DEFAULT 'open', "requirements" jsonb, "availability" jsonb, "searchRadius" numeric(10,2) NOT NULL DEFAULT '25', "expiresAt" TIMESTAMP, "quotesReceived" integer NOT NULL DEFAULT '0', "closedAt" TIMESTAMP, "closureReason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c05f72de8be0ec6b0985a851558" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0328139012f4c96b229026af5e" ON "quote_requests" ("serviceType") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec5f45271b59efe435e7819360" ON "quote_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c4088bbddc918459ea9763090" ON "quote_requests" ("customerId") `);
        await queryRunner.query(`CREATE TABLE "quotes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requestId" uuid NOT NULL, "providerId" uuid NOT NULL, "customerId" uuid NOT NULL, "serviceType" character varying NOT NULL, "description" text NOT NULL, "estimatedPrice" numeric(10,2) NOT NULL, "estimatedDuration" integer NOT NULL DEFAULT '60', "validUntil" TIMESTAMP NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "breakdown" jsonb, "terms" jsonb, "notes" text, "attachments" jsonb, "acceptedAt" TIMESTAMP, "rejectedAt" TIMESTAMP, "rejectionReason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_99a0e8bcbcd8719d3a41f23c263" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e1fc1db17214b25db2adc52ffd" ON "quotes" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccf1feb9e280240bb05dc0aed2" ON "quotes" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9bcf61ad282d63066168f99dc8" ON "quotes" ("providerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_94b283a74da5d28a700add75f0" ON "quotes" ("requestId") `);
        await queryRunner.query(`CREATE TABLE "providers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "businessName" character varying NOT NULL, "description" text NOT NULL, "services" jsonb NOT NULL, "location" jsonb NOT NULL, "serviceRadius" numeric(10,2) NOT NULL DEFAULT '25', "rating" numeric(3,2) NOT NULL DEFAULT '0', "totalReviews" integer NOT NULL DEFAULT '0', "portfolioImages" jsonb, "isBackgroundChecked" boolean NOT NULL DEFAULT false, "isInsured" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "availableHours" jsonb NOT NULL, "pricing" jsonb, "certifications" jsonb, "insurance" jsonb, "completedJobs" numeric(10,2) NOT NULL DEFAULT '0', "responseRate" numeric(5,2) NOT NULL DEFAULT '0', "averageResponseTime" numeric(10,2) NOT NULL DEFAULT '0', "verifiedAt" TIMESTAMP, "verifiedBy" character varying, "rejectedAt" TIMESTAMP, "rejectedBy" character varying, "verificationNotes" text, "adminNotes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_af13fc2ebf382fe0dad2e4793aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_81e454a3ddfad7b389708a081d" ON "providers" ("location") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0a257f97e76b698c4935b27d7" ON "providers" ("userId") `);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL DEFAULT 'direct', "title" character varying, "description" text, "lastMessageId" character varying, "lastMessageAt" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_682fd75da533261f7dac76da8a" ON "conversations" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2973bf1a3c7f304f4aa829bb50" ON "conversations" ("type") `);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversationId" uuid NOT NULL, "senderId" uuid NOT NULL, "receiverId" uuid, "message" text NOT NULL, "messageType" character varying NOT NULL DEFAULT 'text', "attachments" jsonb, "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP, "isDelivered" boolean NOT NULL DEFAULT false, "deliveredAt" TIMESTAMP, "replyToMessageId" uuid, "isEdited" boolean NOT NULL DEFAULT false, "editedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6ce6acdb0801254590f8a78c08" ON "messages" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_acf951a58e3b9611dd96ce8904" ON "messages" ("receiverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2db9cf2b3ca111742793f6c37c" ON "messages" ("senderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e5663ce0c730b2de83445e2fd1" ON "messages" ("conversationId") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "phone" character varying, "profileImage" character varying, "userType" character varying NOT NULL DEFAULT 'customer', "isVerified" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "suspensionReason" character varying, "suspensionComment" text, "suspendedUntil" TIMESTAMP, "emailVerificationToken" character varying, "emailVerificationExpiry" TIMESTAMP, "passwordResetToken" character varying, "passwordResetExpiry" TIMESTAMP, "stripeCustomerId" character varying, "stripePaymentMethodId" character varying, "lastLogin" TIMESTAMP, "settings" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_82bbcdb9c42c5fe140291785c1" ON "users" ("userType") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bookingId" uuid NOT NULL, "customerId" uuid NOT NULL, "providerId" uuid NOT NULL, "rating" numeric(3,2) NOT NULL, "comment" text, "images" jsonb, "criteria" jsonb, "response" text, "respondedAt" TIMESTAMP, "isVerified" boolean NOT NULL DEFAULT false, "isFlagged" boolean NOT NULL DEFAULT false, "flagReason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f4b88c05a7adf404a6e6b2f1eb" ON "reviews" ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c29faa8169d9741d3a1d51483" ON "reviews" ("providerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6d99bdfa69280ede313699fab9" ON "reviews" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c357057587a1c2afae453515bf" ON "reviews" ("bookingId") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" character varying NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "priority" character varying NOT NULL DEFAULT 'medium', "actionUrl" character varying, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "readAt" TIMESTAMP, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_notifications_userId" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE TABLE "app_settings" ("key" character varying NOT NULL, "value" text NOT NULL, "description" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_975c2db59c65c05fd9c6b63a2ab" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "conversation_participants" ("conversationId" uuid NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "PK_e43efbfa3b850160b5b2c50e3ec" PRIMARY KEY ("conversationId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4453e20858b14ab765a09ad728" ON "conversation_participants" ("conversationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_18c4ba3b127461649e5f5039db" ON "conversation_participants" ("userId") `);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "suspensionReason"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "suspensionComment"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "suspendedUntil"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "stripeCustomerId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "stripePaymentMethodId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastLogin"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "suspensionReason" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "suspensionComment" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "suspendedUntil" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "stripeCustomerId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "stripePaymentMethodId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastLogin" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "userType" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_1ead3dc5d71db0ea822706e389d" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_824be6feda5e655c49c4e0c534b" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_a25d33dbd8e95a1875d42ac40c3" FOREIGN KEY ("providerId") REFERENCES "providers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_67b9cd20f987fc6dc70f7cd283f" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_4f8605bc996f6c39ebd7dbead7b" FOREIGN KEY ("providerId") REFERENCES "providers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD CONSTRAINT "FK_3c4088bbddc918459ea9763090e" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotes" ADD CONSTRAINT "FK_94b283a74da5d28a700add75f09" FOREIGN KEY ("requestId") REFERENCES "quote_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotes" ADD CONSTRAINT "FK_9bcf61ad282d63066168f99dc8f" FOREIGN KEY ("providerId") REFERENCES "providers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotes" ADD CONSTRAINT "FK_ccf1feb9e280240bb05dc0aed2a" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "providers" ADD CONSTRAINT "FK_b0a257f97e76b698c4935b27d7d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_e5663ce0c730b2de83445e2fd19" FOREIGN KEY ("conversationId") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_acf951a58e3b9611dd96ce89042" FOREIGN KEY ("receiverId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_4e18c5bd9344f845152f61f5c53" FOREIGN KEY ("replyToMessageId") REFERENCES "messages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_c357057587a1c2afae453515bf6" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_6d99bdfa69280ede313699fab92" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_4c29faa8169d9741d3a1d514830" FOREIGN KEY ("providerId") REFERENCES "providers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "FK_4453e20858b14ab765a09ad728c" FOREIGN KEY ("conversationId") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "FK_18c4ba3b127461649e5f5039dbf" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "FK_18c4ba3b127461649e5f5039dbf"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "FK_4453e20858b14ab765a09ad728c"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_4c29faa8169d9741d3a1d514830"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_6d99bdfa69280ede313699fab92"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_c357057587a1c2afae453515bf6"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_4e18c5bd9344f845152f61f5c53"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_acf951a58e3b9611dd96ce89042"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_e5663ce0c730b2de83445e2fd19"`);
        await queryRunner.query(`ALTER TABLE "providers" DROP CONSTRAINT "FK_b0a257f97e76b698c4935b27d7d"`);
        await queryRunner.query(`ALTER TABLE "quotes" DROP CONSTRAINT "FK_ccf1feb9e280240bb05dc0aed2a"`);
        await queryRunner.query(`ALTER TABLE "quotes" DROP CONSTRAINT "FK_9bcf61ad282d63066168f99dc8f"`);
        await queryRunner.query(`ALTER TABLE "quotes" DROP CONSTRAINT "FK_94b283a74da5d28a700add75f09"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP CONSTRAINT "FK_3c4088bbddc918459ea9763090e"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_4f8605bc996f6c39ebd7dbead7b"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_67b9cd20f987fc6dc70f7cd283f"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_a25d33dbd8e95a1875d42ac40c3"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_824be6feda5e655c49c4e0c534b"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_1ead3dc5d71db0ea822706e389d"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "userType" SET DEFAULT 'customer'`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastLogin"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "stripePaymentMethodId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "stripeCustomerId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "suspendedUntil"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "suspensionComment"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "suspensionReason"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastLogin" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "stripePaymentMethodId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "stripeCustomerId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "suspendedUntil" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "suspensionComment" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "suspensionReason" character varying`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18c4ba3b127461649e5f5039db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4453e20858b14ab765a09ad728"`);
        await queryRunner.query(`DROP TABLE "conversation_participants"`);
        await queryRunner.query(`DROP TABLE "app_settings"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_userId"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c357057587a1c2afae453515bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d99bdfa69280ede313699fab9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c29faa8169d9741d3a1d51483"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4b88c05a7adf404a6e6b2f1eb"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82bbcdb9c42c5fe140291785c1"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5663ce0c730b2de83445e2fd1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2db9cf2b3ca111742793f6c37c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_acf951a58e3b9611dd96ce8904"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ce6acdb0801254590f8a78c08"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2973bf1a3c7f304f4aa829bb50"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_682fd75da533261f7dac76da8a"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0a257f97e76b698c4935b27d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81e454a3ddfad7b389708a081d"`);
        await queryRunner.query(`DROP TABLE "providers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94b283a74da5d28a700add75f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9bcf61ad282d63066168f99dc8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccf1feb9e280240bb05dc0aed2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1fc1db17214b25db2adc52ffd"`);
        await queryRunner.query(`DROP TABLE "quotes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c4088bbddc918459ea9763090"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec5f45271b59efe435e7819360"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0328139012f4c96b229026af5e"`);
        await queryRunner.query(`DROP TABLE "quote_requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67b9cd20f987fc6dc70f7cd283"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f8605bc996f6c39ebd7dbead7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48b267d894e32a25ebde4b207a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_910f39bbc27a3fe62723500c01"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ead3dc5d71db0ea822706e389"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_824be6feda5e655c49c4e0c534"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a25d33dbd8e95a1875d42ac40c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP TABLE "payments"`);
    }

}
