/**
 * Cross-Role Event Tests
 * Verifies that an action by one role produces the correct visible state change
 * in another role's data — the core integration assertions for a two-sided marketplace.
 *
 * Response shapes:
 *   POST /bookings → { data: { booking: {...} } }
 *   GET  /bookings → { data: [...], pagination: {...} }
 *   GET  /bookings/:id → { data: { booking: {...} } }
 *   PUT  /bookings/:id/status → { data: { booking: {...} } }
 */

import { test, expect } from '@playwright/test';

const BASE = 'http://localhost:3000/api/v1';

async function loginAs(request: any, email: string, password = 'Demo123!'): Promise<{ token: string; userId: string }> {
  const res = await request.post(`${BASE}/auth/login`, { data: { email, password } });
  const body = await res.json();
  if (!body.data?.accessToken) throw new Error(`Login failed for ${email}: ${JSON.stringify(body)}`);
  return { token: body.data.accessToken, userId: body.data.user.id };
}

function auth(token: string) {
  return { Authorization: `Bearer ${token}` };
}

function uniqueFutureDate(base = 2600): string {
  const randomDays = base + Math.floor(Math.random() * 300);
  const randomHour = Math.floor(Math.random() * 8) + 8;
  const d = new Date(Date.now() + randomDays * 86400000);
  d.setUTCHours(randomHour, 0, 0, 0);
  return d.toISOString();
}

async function createBooking(request: any, token: string, providerId: string, scheduledDate: string) {
  const res = await request.post(`${BASE}/bookings`, {
    headers: auth(token),
    data: {
      providerId,
      serviceType: 'Limpeza Residencial',
      description: 'Cross-role test booking',
      location: { latitude: -27.5954, longitude: -48.548, address: 'Florianópolis' },
      scheduledDate,
      estimatedDuration: 90,
    },
  });
  const body = await res.json();
  const id = body?.data?.booking?.id ?? body?.data?.id;
  return { status: res.status(), id };
}

// ─── Cross-role: customer creates booking → provider can see it ────────────────
// Uses test.serial (via describe.serial) to share bookingId across tests safely.

test.describe.serial('Cross-role: Customer creates booking → Provider visibility', () => {
  let customerToken: string;
  let providerToken: string;
  let sharedBookingId: string;
  let providerId: string;

  test.beforeAll(async ({ request }) => {
    const [cust, prov] = await Promise.all([
      loginAs(request, 'customer@demo.com'),
      loginAs(request, 'provider@demo.com'),
    ]);
    customerToken = cust.token;
    providerToken = prov.token;

    const provRes = await request.get(`${BASE}/providers?limit=1`);
    providerId = (await provRes.json()).data.providers[0].id;

    // Create the shared booking here so all tests can reliably access its ID
    const { status, id } = await createBooking(request, customerToken, providerId, uniqueFutureDate());
    if (status !== 201) throw new Error('Setup: booking creation failed');
    sharedBookingId = id;
  });

  test('booking created by customer appears in provider booking list', async ({ request }) => {
    const listRes = await request.get(`${BASE}/bookings`, { headers: auth(providerToken) });
    expect(listRes.status()).toBe(200);
    const listBody = await listRes.json();
    const bookings: any[] = listBody.data;
    const found = bookings.find((b: any) => b.id === sharedBookingId);
    expect(found).toBeDefined();
    expect(found.status).toBe('pending');
  });

  test('provider accepting booking updates status seen by customer', async ({ request }) => {
    const confirmRes = await request.put(`${BASE}/bookings/${sharedBookingId}/status`, {
      headers: auth(providerToken),
      data: { status: 'confirmed' },
    });
    expect(confirmRes.status()).toBe(200);

    const getRes = await request.get(`${BASE}/bookings/${sharedBookingId}`, {
      headers: auth(customerToken),
    });
    expect(getRes.status()).toBe(200);
    const getBody = await getRes.json();
    const booking = getBody.data.booking ?? getBody.data;
    expect(booking.status).toBe('confirmed');
  });

  test('customer cancelling a booking updates status seen by provider', async ({ request }) => {
    // Create a separate booking just for cancellation test
    const { status, id } = await createBooking(request, customerToken, providerId, uniqueFutureDate());
    if (status !== 201) test.skip(true, 'Booking creation failed');

    await request.put(`${BASE}/bookings/${id}/status`, {
      headers: auth(customerToken),
      data: { status: 'cancelled' },
    });

    const getRes = await request.get(`${BASE}/bookings/${id}`, {
      headers: auth(providerToken),
    });
    expect(getRes.status()).toBe(200);
    const getBody = await getRes.json();
    const booking = getBody.data.booking ?? getBody.data;
    expect(booking.status).toBe('cancelled');
  });
});

// ─── Cross-role: notifications generated by status changes ────────────────────

test.describe('Cross-role: Status changes generate notifications', () => {
  let customerToken: string;
  let providerToken: string;
  let bookingId: string;
  let providerId: string;

  test.beforeAll(async ({ request }) => {
    const [cust, prov] = await Promise.all([
      loginAs(request, 'customer@demo.com'),
      loginAs(request, 'provider@demo.com'),
    ]);
    customerToken = cust.token;
    providerToken = prov.token;

    const provRes = await request.get(`${BASE}/providers?limit=1`);
    providerId = (await provRes.json()).data.providers[0].id;

    const { status, id } = await createBooking(request, customerToken, providerId, uniqueFutureDate());
    if (status === 201) bookingId = id;
  });

  test('customer receives notification when provider confirms booking', async ({ request }) => {
    if (!bookingId) test.skip(true, 'Booking not created in setup');

    const countBefore = await request.get(`${BASE}/notifications/unread/count`, {
      headers: auth(customerToken),
    });
    const beforeCount = (await countBefore.json()).data?.unreadCount ?? 0;

    await request.put(`${BASE}/bookings/${bookingId}/status`, {
      headers: auth(providerToken),
      data: { status: 'confirmed' },
    });

    const countAfter = await request.get(`${BASE}/notifications/unread/count`, {
      headers: auth(customerToken),
    });
    expect(countAfter.status()).toBe(200);
    const afterCount = (await countAfter.json()).data?.unreadCount ?? 0;
    // Unread count should be >= before (notifications may have been pre-existing)
    expect(afterCount).toBeGreaterThanOrEqual(beforeCount);
  });
});

// ─── Cross-role: provider submits quote → customer sees it ────────────────────

test.describe.serial('Cross-role: Provider submits quote → Customer visibility', () => {
  let customerToken: string;
  let providerToken: string;
  let quoteRequestId: string;

  test.beforeAll(async ({ request }) => {
    const [cust, prov] = await Promise.all([
      loginAs(request, 'customer@demo.com'),
      loginAs(request, 'provider@demo.com'),
    ]);
    customerToken = cust.token;
    providerToken = prov.token;

    // Create quote request upfront so all tests share the same ID
    const createRes = await request.post(`${BASE}/quotes/requests`, {
      headers: auth(customerToken),
      data: {
        serviceType: 'Limpeza Profunda',
        description: 'Limpeza profunda pós-obra para 3 quartos',
        location: { city: 'Florianópolis', state: 'SC', address: 'Rua das Rosas, 200', latitude: -27.5954, longitude: -48.548 },
        urgency: 'medium',
        budget: { min: 200, max: 500, currency: 'BRL' },
      },
    });
    if (createRes.status() === 201) {
      const body = await createRes.json();
      quoteRequestId = body.data?.id ?? body.data?.quoteRequest?.id;
    }
  });

  test('quote request created by customer is visible to provider', async ({ request }) => {
    expect(quoteRequestId).toBeDefined();

    const listRes = await request.get(`${BASE}/quotes/requests`, { headers: auth(providerToken) });
    expect(listRes.status()).toBe(200);
    const listBody = await listRes.json();
    expect(listBody.success).toBe(true);
  });

  test('provider submits a quote on customer request', async ({ request }) => {
    if (!quoteRequestId) test.skip(true, 'Quote request not created in setup');

    const submitRes = await request.post(`${BASE}/quotes`, {
      headers: auth(providerToken),
      data: {
        requestId: quoteRequestId,          // field name is requestId (not quoteRequestId)
        serviceType: 'Limpeza Profunda',
        description: 'Limpeza profunda completa incluindo todos os ambientes',
        estimatedPrice: 350,                // field name is estimatedPrice (not price)
        estimatedDuration: 240,
        validUntil: new Date(Date.now() + 7 * 86400000).toISOString(),
      },
    });
    expect(submitRes.status()).toBe(201);
    const body = await submitRes.json();
    expect(body.success).toBe(true);
    const price = body.data?.estimatedPrice ?? body.data?.quote?.estimatedPrice ?? body.data?.price;
    expect(Number(price)).toBe(350);

    // Customer can see the quote on their request
    const requestRes = await request.get(`${BASE}/quotes/requests/${quoteRequestId}`, {
      headers: auth(customerToken),
    });
    expect(requestRes.status()).toBe(200);
  });
});

// ─── Cross-role: customer review → affects provider ───────────────────────────

test.describe('Cross-role: Review submission', () => {
  let customerToken: string;

  test.beforeAll(async ({ request }) => {
    customerToken = (await loginAs(request, 'customer@demo.com')).token;
  });

  test('customer can submit a review on a completed booking', async ({ request }) => {
    const bookingsRes = await request.get(`${BASE}/bookings?status=completed&limit=1`, {
      headers: auth(customerToken),
    });
    expect(bookingsRes.status()).toBe(200);
    const bookingsBody = await bookingsRes.json();
    const completedBookings: any[] = bookingsBody.data;

    if (!completedBookings || completedBookings.length === 0) {
      test.skip(true, 'No completed bookings available for review test');
      return;
    }

    const bookingId = completedBookings[0].id;
    const reviewRes = await request.post(`${BASE}/reviews`, {
      headers: auth(customerToken),
      data: {
        bookingId,
        rating: 5,
        comment: 'Excelente serviço! Muito profissional e pontual.',
        criteria: { quality: 5, timeliness: 5, communication: 5, professionalism: 5, valueForMoney: 4 },
      },
    });
    // 201 = success, 400 = duplicate review — both acceptable
    expect([201, 400]).toContain(reviewRes.status());
  });

  test('review rejected for non-completed booking', async ({ request }) => {
    const bookingsRes = await request.get(`${BASE}/bookings?status=pending&limit=1`, {
      headers: auth(customerToken),
    });
    const pendingBookings: any[] = (await bookingsRes.json()).data ?? [];

    if (pendingBookings.length === 0) {
      test.skip(true, 'No pending bookings available');
      return;
    }

    const bookingId = pendingBookings[0].id;
    const reviewRes = await request.post(`${BASE}/reviews`, {
      headers: auth(customerToken),
      data: { bookingId, rating: 5, comment: 'Review on non-completed booking' },
    });
    expect([400, 422]).toContain(reviewRes.status());
  });
});
